### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Qasimmodo** [circa94/JSlither#10]
root@server:[~/JSlither]: npm start

> JSlither@1.0.0 start /root/JSlither
> node server.js

/root/JSlither/node_modules/ws/lib/WebSocketServer.js:44
    throw new TypeError('`port` or a `server` must be provided');
    ^

TypeError: `port` or a `server` must be provided
    at new WebSocketServer (/root/JSlither/node_modules/ws/lib/WebSocketServer.js:44:11)
    at SlitherServer (/root/JSlither/server.js:23:14)
    at Object.<anonymous> (/root/JSlither/server.js:217:1)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)
    at startup (node.js:146:18)
    at node.js:404:3

**Comment by circa94** [comment]
please look at issue: https://github.com/circa94/JSlither/issues/8 

there is a workaround
